version: '2'
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless-debug:15.3.1
    container_name: teleport
    hostname: teste
    ports:
      - "3023:3023"
      - "3025:3025"
      - "80:3080"
    volumes:
      - ./config:/etc/teleport
      - ./teleport.yaml:/etc/teleport/teleport.yaml 
      - ./data:/var/lib/teleport
      - ./certbot/www/:/var/www/certbot/:ro
    networks:
      - teleport-net
      
  ssh_server:
    build: .
    ports:
      - "2222:22"
    container_name: ssh_server

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.ng
    image: jorgerabello/nginx:reverseproxy
    container_name: nginx
    networks:
      - nodeappnet
    ports:
      - "8080:80"
    depends_on:
      - teleport    

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot

networks:
  teleport-net:
    driver: bridge