version: '2'
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless-debug:15.3.1
    container_name: teleport
    hostname: teste
    labels:
      - traefik.enable=true
      - traefik.port=3080
      - traefik.http.routers.bean_site.tls=true
      - traefik.http.routers.bean_site.rule=Host(`teleport.beansoftwares.com.br`)
      - traefik.http.routers.bean_site.tls.certresolver=lets-encrypt
      - traefik.http.services.bean_site.loadbalancer.server.port=3080
    ports:
      - "3023:3023"
      - "3025:3025"
      - "3080:3080"
    volumes:
      - ./config:/etc/teleport
      - ./teleport.yaml:/etc/teleport/teleport.yaml 
      - ./data:/var/lib/teleport
    networks:
      - teleport-net
      - traefik-proxy
      
  ssh_server:
    build: .
    ports:
      - "2222:22"
    container_name: ssh_server
  
 reverse-proxy:
    build: 
      context: .
      dockerfile: Dockerfile.ng
    container_name: reverse-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    name: traefik-proxy
  teleport-net:
    driver: bridge