version: '2'
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless-debug:15.3.1
    container_name: teleport
    hostname: teste
    labels:
      - traefik.http.routers.teleport.rule=Host(`teleport.beansoftwares.com.br`)
    ports:
      - "3023:3023"
      - "3025:3025"
      - "3080:3080"
    volumes:
      - ./config:/etc/teleport
      - ./teleport.yaml:/etc/teleport/teleport.yaml 
      - ./data:/var/lib/teleport
    networks:
      - teleport-net
      
  ssh_server:
    build: .
    ports:
      - "2222:22"
    container_name: ssh_server
  
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    restart: always
    command:
      - "--log.level=ERROR"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml"

networks:
  teleport-net:
    driver: bridge