version: '2'
services:
 reverse-proxy:
    build: 
      context: .
      dockerfile: Dockerfile.ng
    container_name: reverse-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:                                                          
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    name: traefik-proxy
