[http.middlewares]
  [http.middlewares.midHeaders.headers]
    frameDeny = true
    browserXSSFilter = true
    contentTypeNosniff = true
    stsPreload = true
    stsIncludeSubdomains = true
    stsSeconds = 15552000
    forceSTSHeader = true

  [http.middlewares.midRateLimit]
    [http.middlewares.midRateLimit.rateLimit]
      average = 10
      burst = 10

  [http.middlewares.midRedirectHTTPToHTTPS.redirectScheme]
    scheme = "https"
    permanent = true

  [http.middlewares.midRedirectHTTPSToHTTP.redirectScheme]
    scheme = "http"
    permanent = true

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"

  [tls.options.mintls12]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_AES_128_GCM_SHA256",
      "TLS_AES_256_GCM_SHA384",
      "TLS_CHACHA20_POLY1305_SHA256"
    ]
    sniStrict = true